# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DemoApp
  pod 'Firebase/Core'
  pod 'FirebaseDatabase'

  target 'DemoApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'DemoApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DemoApp-tvOS


end
